Controllers/PurchaseController.cs
using InventoryManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventoryManagementSystem.Controllers
{
    public class PurchaseController : Controller
    {
        Inventory_SystemEntities db = new Inventory_SystemEntities();

        // GET: Purchase
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult DisplayPurchase()
        {
            List<purchase> purchaselist = new List<purchase>();
            purchaselist = db.purchases.OrderByDescending(x => x.ID).ToList();
            return View(purchaselist);
        }
        [HttpGet]
        public ActionResult PurchaseProduct()
        {
            List<string> productnamelist = new List<string>();
            productnamelist = db.products.Select(x => x.Product_Name).ToList();
            ViewBag.productname = new SelectList(productnamelist);
            return View();
        }
        [HttpPost]
        public ActionResult PurchaseProduct(purchase pur)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.purchases.Add(pur);
                    db.SaveChanges();
                    TempData["successmessage"] = "Record saved successfully..";
                }
                else
                {
                    TempData["errormessage"] = "Record not saved..";
                }


            }
            catch (Exception ex)
            {
                TempData["errormessage"] = ex.Message;
            }

            return RedirectToAction("DisplayPurchase");
        }
        //Update product
        [HttpGet]
        public ActionResult UpdatePurchaseProduct(int id)
        {
            purchase pr = new purchase();
            try
            {

                pr = db.purchases.Where(x => x.ID == id).SingleOrDefault();
            }
            catch (Exception ex)
            {

                TempData["errormessage"] = ex.Message;
            }

            return View(pr);
        }
        [HttpPost]
        public ActionResult UpdatePurchaseProduct(purchase pr)
        {
            try
            {
                purchase objpr = new purchase();
                objpr = db.purchases.Where(x => x.ID == pr.ID).SingleOrDefault();

                if (objpr != null)
                {
                    objpr.Purchase_Prod = pr.Purchase_Prod;
                    objpr.Purchase_Qnty = pr.Purchase_Qnty;
                    objpr.Purchase_Date = pr.Purchase_Date;
                    db.SaveChanges();
                    TempData["successmessage"] = "Record Updated successfully..";
                }
                else
                {
                    TempData["errormessage"] = "Purchase Product not Updated..";
                }
            }
            catch (Exception ex)
            {
                TempData["errormessage"] = ex.Message;
            }

            return RedirectToAction("DisplayPurchase");
        }
        //Details product
        [HttpGet]
        public ActionResult DetailsPurchaseProduct(int id)
        {
            purchase pr = new purchase();
            try
            {

                pr = db.purchases.Where(x => x.ID == id).SingleOrDefault();
            }
            catch (Exception ex)
            {

                TempData["errormessage"] = ex.Message;
            }

            return View(pr);
        }
        //Delete product
        [HttpGet]
        public ActionResult DeletePurchaseProduct(int id)
        {
            purchase pr = new purchase();
            try
            {

                pr = db.purchases.Where(x => x.ID == id).SingleOrDefault();
            }
            catch (Exception ex)
            {

                TempData["errormessage"] = ex.Message;
            }

            return View(pr);
        }

        [HttpPost]

        public ActionResult DeletePurchaseProduct(int id, purchase pro)
        {
            try
            {

                purchase pr = new purchase();

                pr = db.purchases.Remove(db.purchases.Where(x => x.ID == id).SingleOrDefault());
                db.purchases.Remove(pr);
                db.SaveChanges();
                TempData["successmessage"] = "Record deleted successfully..";
            }
            catch (Exception ex)
            {
                TempData["errormessage"] = ex.Message;
            }

            return RedirectToAction("DisplayPurchase");

        }
    }
}

Controllers/SaleController.cs
using InventoryManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventoryManagementSystem.Controllers
{
    public class SaleController : Controller
    {
        // GET: Sale

        Inventory_SystemEntities db = new Inventory_SystemEntities();

        // GET: Purchase
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult DisplaySaleProduct()
        {
            List<Sale> Saleslist = new List<Sale>();
            Saleslist = db.Sales.OrderByDescending(x => x.ID).ToList();
            return View(Saleslist);
        }
        [HttpGet]
        public ActionResult SaleProduct()
        {
            List<string> list = new List<string>();
            list = db.products.Select(x => x.Product_Name).ToList();
            ViewBag.productname = new SelectList(list);
            return View();
        }
        [HttpPost]
        public ActionResult SaleProduct(Sale sal)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Sales.Add(sal);
                    db.SaveChanges();
                    TempData["successmessage"] = "Record saved successfully..";
                }
                else
                {
                    TempData["errormessage"] = "Record not saved..";
                }


            }
            catch (Exception ex)
            {
                TempData["errormessage"] = ex.Message;
            }

            return RedirectToAction("DisplaySaleProduct");
        }
        //Update product
        [HttpGet]
        public ActionResult UpdateSaleProduct(int id)
        {
            Sale sal = new Sale();
            try
            {

                sal = db.Sales.Where(x => x.ID == id).SingleOrDefault();
            }
            catch (Exception ex)
            {

                TempData["errormessage"] = ex.Message;
            }

            return View(sal);
        }
        [HttpPost]
        public ActionResult UpdateSaleProduct(Sale sal)
        {
            try
            {

                Sale s = new Sale();
                s = db.Sales.Where(x => x.ID == sal.ID).SingleOrDefault();
                if (s != null)
                {
                    s.Sale_Prod = sal.Sale_Prod;
                    s.Sale_Qnty = sal.Sale_Qnty;
                    s.Sale_Date = sal.Sale_Date;
                    db.SaveChanges();
                    TempData["successmessage"] = "Record Updated successfully..";
                }
                else
                {
                    TempData["successmessage"] = "Record Not Updated..";
                }

            }
            catch (Exception ex)
            {
                TempData["errormessage"] = ex.Message;
            }

            return RedirectToAction("DisplaySaleProduct");
        }
        //Details product
        [HttpGet]
        public ActionResult DetailsSaleProduct(int id)
        {
            Sale sal = new Sale();
            try
            {

                sal = db.Sales.Where(x => x.ID == id).SingleOrDefault();
            }
            catch (Exception ex)
            {

                TempData["errormessage"] = ex.Message;
            }

            return View(sal);
        }
        //Delete product
        [HttpGet]
        public ActionResult DeleteSaleProduct(int id)
        {
            Sale sal = new Sale();
            try
            {

                sal = db.Sales.Where(x => x.ID == id).SingleOrDefault();
            }
            catch (Exception ex)
            {

                TempData["errormessage"] = ex.Message;
            }

            return View(sal);
        }

        [HttpPost]
        public ActionResult DeleteSaleProduct(int id, Sale sal)
        {
            try
            {

                Sale sa = new Sale();
                sa = db.Sales.Remove(db.Sales.Where(x => x.ID == id).SingleOrDefault());
                db.Sales.Remove(sa);
                db.SaveChanges();
                TempData["successmessage"] = "Record deleted successfully..";
            }
            catch (Exception ex)
            {
                TempData["errormessage"] = ex.Message;
            }

            return RedirectToAction("DisplaySaleProduct");

        }
    }
}

Controllers/productController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using InventoryManagementSystem.Models;

namespace InventoryManagementSystem.Controllers
{
    public class productController : Controller
    {
        Inventory_SystemEntities db = new Inventory_SystemEntities();
        // GET: product
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult DisplayProduct()
        {
            List<product> productList = new List<product>();
            productList = db.products.OrderByDescending(x => x.ID).ToList();

            return View(productList);
        }

        [HttpGet]
        public ActionResult CreateProduct()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateProduct(product pro)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.products.Add(pro);
                    db.SaveChanges();
                    TempData["successmessage"] = "Product saved successfully..";
                }
                else
                {
                    TempData["errormessage"] = "Product not saved..";
                }


            }
            catch (Exception ex)
            {
                TempData["errormessage"] = ex.Message;
            }

            return RedirectToAction("DisplayProduct");
        }
        //Update product
        [HttpGet]
        public ActionResult UpdateProduct(int id)
        {
            product pr = new product();
            try
            {

                pr = db.products.Where(x => x.ID == id).SingleOrDefault();
            }
            catch (Exception ex)
            {

                TempData["errormessage"] = ex.Message;
            }

            return View(pr);
        }
        [HttpPost]
        public ActionResult UpdateProduct(product pro)
        {
            try
            {
                product pr = new product();
                pr = db.products.Where(x => x.ID == pro.ID).SingleOrDefault();
                if (ModelState.IsValid)
                {
                    pr.Product_Name = pro.Product_Name;
                    pr.Product_Qnty = pro.Product_Qnty;
                    db.SaveChanges();
                    TempData["successmessage"] = "Product Updated successfully..";
                }
                else
                {
                    TempData["errormessage"] = "Product not Updated..";
                }


            }
            catch (Exception ex)
            {
                TempData["errormessage"] = ex.Message;
            }

            return RedirectToAction("DisplayProduct");
        }
        //Details product
        [HttpGet]
        public ActionResult DetailsProduct(int id)
        {
            product pr = new product();
            try
            {

                pr = db.products.Where(x => x.ID == id).SingleOrDefault();
            }
            catch (Exception ex)
            {

                TempData["errormessage"] = ex.Message;
            }

            return View(pr);
        }
        //Delete product
        [HttpGet]
        public ActionResult DeleteProduct(int id)
        {
            product pr = new product();
            try
            {

                pr = db.products.Where(x => x.ID == id).SingleOrDefault();
            }
            catch (Exception ex)
            {

                TempData["errormessage"] = ex.Message;
            }

            return View(pr);
        }

        [HttpPost]

        public ActionResult DeleteProduct(int id, product pro)
        {
            try
            {

                product pr = new product();

                pr = db.products.Remove(db.products.Where(x => x.ID == id).SingleOrDefault());
                db.products.Remove(pr);
                db.SaveChanges();
                TempData["successmessage"] = "Product deleted successfully..";
            }
            catch (Exception ex)
            {
                TempData["errormessage"] = ex.Message;
            }

            return RedirectToAction("DisplayProduct");

        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/css/bootstrap.min.css' />

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
           
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <div id="Menu1">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>
                            <a class="popout" href="#">Transactions</a><ul class="level2 dropdown-menu">
                                <li>@Html.ActionLink("Product Master", "DisplayProduct", "product")</li>
                                <li>@Html.ActionLink("Purchase Master", "DisplayPurchase", "Purchase")</li>
                                <li>@Html.ActionLink("Sale Master", "DisplaySaleProduct", "Sale")</li>
                            </ul>
                        </li>
                        <li>
                            <a href="~/ProductReportView.aspx">Product Report</a>
                            @*<a class="popout" href="#">Reports</a><ul class="level3 dropdown-menu">
                                <li>@Html.ActionLink("Product Master", "DisplayProduct", "product")</li>
                                <li>@Html.ActionLink("Purchase Master", "DisplayPurchase", "Purchase")</li>
                                <li>@Html.ActionLink("Sale Master", "DisplaySaleProduct", "Sale")</li>
                            </ul>*@

                        </li>
                        
                    </ul>
                </div>
            </div>
        </div>

    </div>
    <script type="text/javascript" src='https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.3.min.js'></script>
    <script type="text/javascript" src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/js/bootstrap.min.js'></script>
    <script type="text/javascript">
        $(function () {
            //Remove the style attributes.
            $(".navbar-nav li, .navbar-nav a, .navbar-nav ul").removeAttr('style');

            //Apply the Bootstrap class to the Submenu.
            $(".dropdown-menu").closest("li").removeClass().addClass("dropdown-toggle");

            //Apply the Bootstrap properties to the Submenu.
            $(".dropdown-toggle").find("a").eq(0).attr("data-toggle", "dropdown").attr("aria-haspopup", "true").attr("aria-expanded", "false").append("<span class='caret'></span>");

            //Apply the Bootstrap "active" class to the selected Menu item.
            $("a.selected").closest("li").addClass("active");
            $("a.selected").closest(".dropdown-toggle").addClass("active");
        });
    </script>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

        @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)*@

</body>
</html>